config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  mount_uploader :image, ImageUploader

  validates :body, presence: true, unless: :image?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    # binding.pry
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)

    respond_to do |format|
      format.html
      format.json
    end

  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save

      respond_to do |format|
        format.html { redirect_to group_message_path(@message), notice: 'メッセージの投稿が完了しました。' }
        format.json
      end

    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    /
      <div class='chat-group-form__field--left'>
      <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
      </div>
      <div class='chat-group-form__field--right'>
      <div class='chat-group-form__search clearfix'>
      <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
      </div>
      <div id='user-search-result'></div>
      </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div id='chat-group-users'>
        <div class='chat-group-user clearfix' id='chat-group-user-22'>
        <input name='chat_group[user_ids][]' type='hidden' value='22'>
        <p class='chat-group-user__name'>seo_kyohei</p>
        </div>
        </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.chat
  =render 'layouts/sidebar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_flash.html.haml
.flash-messages
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_sidebar.html.haml
.chat-side
  .chat-user.clearfix
    %h5
      = current_user.name
    .chat-user__actions
      = link_to new_group_path, class: 'chat-user__action' do
        %i.fa.fa-pencil-square-o
      = link_to edit_user_path(current_user), class: 'chat-user__action' do
        %i.fa.fa-cog
  = render '/layouts/sidebar/group'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/flash'
    = yield

app/views/layouts/sidebar/_group.html.haml
%ul.chat_groups
  %li.chat-group
    - current_user.groups.each do |group|
      = link_to group_messages_path(group), class: 'chat-group__link' do
        %p.chat-group__name
          = group.name
        %p.chat-group__message
          = group.show_last_message

app/views/messages/_message.html.haml
%li.chat-message
  .chat-message__header.clearfix
    %p.chat-message__name
      = message.user.name
    %p.chat-message__time
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  %p.chat-message__body
    = message.body
  = image_tag message.image.url if message.image.present?

app/views/messages/index.html.haml
.chat
  =render 'layouts/sidebar'
  .chat-main
    .chat-header.clearfix
      .chat-header--left
        %h2
          = @group.name
        %p.chat-header__users
          Members:
          %span.chat-header__user
            = @group.users.pluck(:name).join(' ')
      .chat-header--right
        = link_to 'Edit', '#', class: 'chat-header__edit-btn'
    .chat-body
      %ul.chat-messages
        =render @messages
    .chat-footer.clearfix
      = form_for [@group, @message] do |f|
        = f.text_field :body, class: 'textarea form_message', autofocus: true, placeholder: 'type a message'
        %label.form__mask
          .fa.fa-image
          = f.file_field :image, class: 'message_image'
        = f.submit 'Send', class: 'submit-save'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'